### PR TITLE
Update composer.json & travis.yml

### PR DESCRIPTION
**Pull request by HMAZonderland**
Limited the phpunit version to max 5.7.20 to fix Travis

### CODE REVIEW

**Comment by Peardian** [comment]
Interesting changes. It looks good for the most part, though I am curious about why the minimum version of PHPUnit is set to 4. Is there something wrong with 3.7, aside from being old?

**Comment by HMAZonderland** [comment]
There has to be a cap at phpunit 5.7.* otherwise composer will load phpunit 6 which breaks everything.

**Comment by HMAZonderland** [comment]
You can stick with 3.7 if you are that much attached to it. ;-)

**Comment by Peardian** [comment]
Ha, okay. I'll see about getting it merged on Friday if time (and weather) permits.

**Comment by Peardian** [comment]
Merged! Thanks for the contribution.

**Pull request merged**
