### PR TITLE
add possibility to list orders from multiple market places

### PR DESCRIPTION
**Pull request by gutsverwalter**

### CODE REVIEW

**Comment by Peardian** [comment]
Thank you for the contribution. At a glance, the code looks good and the feature seems to fit in. Unfortunately, I am not able to look at it more in-depth at this time. I am not too familiar with how different marketplaces work in Amazon, as so far I have only dealt with single-marketplace stores.

**Comment by gutsverwalter** [comment]
I have tested it. Without this merge the default market place will be taken, so you will only get a list of orders of your default market place. With this merge your list of orders might be bigger, because you also receive orders from the other market places. It's annoying if you want to fetch the orders that changed in the last 24 hours and you only receive those from one market place.

**Comment by Peardian** [comment]
It's unfortunate that there is no way to just say "give me all marketplaces" because it is a required parameter. Anyway, it will still be a while before I am able to do anything with this pull request, but rest assured that it will not be forgotten.

**Comment by Peardian** [comment]
Marketplace support has been added for Orders, as well as for a couple of other objects with the marketplace filter parameter. Unfortunately, I was not able to use this code, but I still appreciate the attempt and thank you for bringing the issue to light.

**Pull request closed without merging**
