### PR TITLE
Update AmazonProductFeeEstimate.php

### PR DESCRIPTION
**Pull request by luigel**
Edited the option key for the listing prices so the amazon can get the data. Refer to the scratchpad product api labels.

### CODE REVIEW

**Comment by Peardian** [comment]
Looks like I messed up the option names when adding that class. Thanks for the finding and fixing it!

Would you mind also fixing the `AmazonProductFeeEstimateTest` unit test real quick to make Travis happy? The test is expecting the old option names, so fixing it would be as easy as swapping in the new names. I would greatly appreciate it if you could. If not, I understand. I can fix it on my own if needbe.

**Comment by Peardian** [comment]
@luigel Thank you for combining the merge requests. As you can see, you simply need to push the changes to your `patch-1` branch to update the pull request.

It looks like the one unit test is still failing. Could you try fixing it again? If it proves to be too difficult for you, I can try fixing them myself on Friday.

**Comment by luigel** [comment]
@Peardian Sorry I tried to fixed it in my latest push in the `patch-1`. Can you try it if it is now working. If not I would like your help for it. Thank you. Good day.

**Comment by Peardian** [comment]
Thank you! The tests pass now, so there will be no problem in merging it. I should have it merged by the end of the week. Thank you for your contribution!

**Pull request merged**
